image: $SKA_K8S_TOOLS_DOCKER_BUILDER_IMAGE

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - test
  - build
  - publish
  - pages

include:
    # Tag Based GitLab Release Management
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/release.gitlab-ci.yml'
    # .post step finalisers eg: badges
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

python-lint:
  image: python:3.8
  stage: lint
  before_script:
    - pip3 install black
  script:
    - black --check src/ tests/
  artifacts:
    paths:
      - build
    expire_in: 1 week
    when: always

python-test:
  image: python:3.8
  stage: test
  except:
    - tags
  tags:
    - k8srunner
  before_install:
    - pip install poetry
    - poetry install -v
  script:
    - pytest tests/test_end_to_end_fourier_transform.py
  after_script:
    - mkdir -p build/reports
    - mv unit-tests.xml build/reports
  environment:
    name: test/$CI_COMMIT_REF_NAME
    kubernetes:
      namespace: $KUBE_NAMESPACE
  artifacts:
    paths:
      - build
    expire_in: 1 week
    when: always