[tool.poetry]
name = "ska-sdp-distributed-fourier-transform"
version = "0.0.0"
description = "SKA SDP Distributed Fourier Transform"
authors = ["SKA SDP Developers"]
license = "BSD-3-Clause"
repository = "https://gitlab.com/ska-telescope/sdp/ska-sdp-distributed-fourier-transform"

[tool.poetry.dependencies]
python = "^3.9.5"
bokeh = "^2.4.2"
dask = "^2022.03.0"
distributed = "^2022.3.0"
jupyter = "^1.0.0"
matplotlib = "^3.5.1"
numpy = "^1.22.3"
scipy = {version="^1.8.0", python=">=3.9.5,<3.11"}
h5py = "^3.6.0"
pandas = "^1.4.2"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^22.1.0"
flake8 = "^4.0.1"
pylint = "^2.12.2"
pylint-junit = "^0.3.2"
pytest = "^7.0.1"
pytest-cov = "^3.0.0"
build = "^0.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
